### ISSUE TITLE
makeFileList.py won't let any dev video out

### ISSUE THREAD

**Issue by BehnazDibayee** [joonson/syncnet_trainer#15]
Hi,

I'm about to train the model with Voxceleb2 dataset just to monitor the train pipeline. 
I run this command on dev set:
python ./makeFileList.py --output data/dev.txt --mp4_dir VOX2_PATH/dev/mp4 --txt_dir VOX2_PATH/dev/txt --wav_dir VOX2_PATH/dev/wav

But for all files I'm getting this error :
__Skipped ./vox2celeb/dev/mp4/id04484/ex2J3Oq2CAE/00084.mp4 - audio and video lengths different__

I worth mentioning that I had extracted the .wav files from mp4 files by using ffmpeg instead of downloading audio files.

Could anyone help please?

**Comment by BehnazDibayee** [comment]
That was because of my ffmpeg version. It was too old (2.1.18)

I installed a new version and problem solved.

**Comment by richardblythman** [comment]
Hi @BehnazDibayee. What version of ffmpeg did you use? I am having the same issue using 2.8.17. Also, I extracted the .wav from the downloaded .aac files.
